GET http://localhost:8080/assets

### get sum for assets by category
GET http://localhost:8080/assets/sum/category

### Delete assets
DELETE http://localhost:8080/assets/55719200-5328-455b-b74d-1c31cb8a1a11

###
POST http://localhost:8080/assets
Content-Type: application/json

[
  {
    "amount": 100.0,
    "category": "RENT",
    "incomeDate": "2020-02-02T10:10:10.001Z",
    "description": "desc"
  },{
  "amount": 101.0,
  "category": "RENT",
  "incomeDate": "2020-02-02T10:10:10.001Z",
  "description": "desc"
  }
]

### PUT Asset
PUT http://localhost:8080/assets
Content-Type: application/json

{
  "id": "37a9b49b-a18f-4013-a1a7-59141916d034",
  "amount": 100.0,
  "category": "RENT",
  "incomeDate": "2020-03-02T10:10:10.001Z",
  "description": "desc"
}

### GET All Expenses Category
GET http://localhost:8080/expenses/category

### GET All Expenses
GET  http://localhost:8080/expenses

### Delete Expense
DELETE http://localhost:8080/expenses/69b22b00-ae72-4202-95d5-97d2e8726aae

### POST Expense
POST http://localhost:8080/expenses
Content-Type: application/json

[
  {
    "amount": 200,
    "description": "some desc",
    "purchaseDate": "2020-02-02T10:10:10.001Z",
    "expensesCategory": "OTHERS"
  }
]

### PUT Expense
PUT http://localhost:8080/expenses
Content-Type: application/json

  {
    "id": "dffb93d9-c105-48db-a672-90fda501311d",
    "amount": 1200,
    "description": "so",
    "purchaseDate": "2020-02-02T10:10:10.001Z",
    "expensesCategory": "FUN"
  }


### GET All Expenses by category
GET  http://localhost:8080/expenses/filter?category=fun
